### ISSUE TITLE
Color output when stdout is interactive

### ISSUE THREAD

**Issue by hdamron17** [jyn514/GrepMe#12]
See https://docs.python.org/3.6/library/os.html#os.isatty

**Comment by jyn514** [comment]
What would we color? This isn't code, there's no syntax. Would you like names to be coloured or something?

**Comment by hdamron17** [comment]
Coloring the matched text when the -o flag is not used. Just like Gnu grep with —color flag (—color=auto by default). This makes matches easier to view in text with long lines.

**Comment by jyn514** [comment]
Forgot that was a thing. This will be even more useful now that `--context` works.
