### ISSUE TITLE
Filter only liked messages

### ISSUE THREAD

**Issue by hdamron17** [jyn514/GrepMe#14]
This will be very helpful in narrowing search query if you remember liking the message.

**Comment by hdamron17** [comment]
This should be labeled idea but I can’t figure out how to do that on the mobile GitHub site.

**Comment by jyn514** [comment]
Because groupme is annoying, I have to know user ids, I can't just search 'liked by self'. So I'm going to implement this as 'liked by' and have the default user be you. Example of what I'm talking about:

```
{'attachments': [], 'avatar_url': 'https://i.groupme.com/3280x2460.jpeg.e2280ee7c6334088845b91703e46da9c', 'created_at': 1551937708, 'favorited_by': ['19838525', '29652195'],
...
'user_id': '19821026', 'platform': 'gm'}
```

**Comment by jyn514** [comment]
Also added the opposite, only messages you haven't liked.
