### ISSUE TITLE
Add more flags

### ISSUE THREAD

**Issue by jyn514** [jyn514/GrepMe#3]
- [ ] Reverse matching: `-v`
- [x] Only matching: [`-o`](https://github.com/jyn514/GrepMe/commit/5e638af90a2609f92d5921d20029bb74fde74f27)
- [x] Users: [`-u`](https://github.com/jyn514/GrepMe/commit/d8ae31124d3fad65ee8478518da9e1e9c855d2b5)
- [x] Context: [`-A`, `-B`](https://github.com/jyn514/GrepMe/commit/3eea1e6601bb16475c74820929760628b822880e), [`-C`](https://github.com/jyn514/GrepMe/commit/ba66c73cc240570fcd1985d8ef44611b0a251f34) flags
- [x] [Ignore case: `-i`](https://github.com/jyn514/GrepMe/commit/8fd23584ac47ddbcd4e5cfbb86efb465d35a72a3)

**Comment by hdamron17** [comment]
Added ignore case flag because I wanted to use GrepMe and I rarely use grep without -i. See #8.

**Comment by jyn514** [comment]
Thought of a way to do context: at the beginning, allocate a buffer of `-A + -B` long, then treat it as a circular list as we go through. Then the only hard part is knowing where the buffer starts and ends.

**Comment by jyn514** [comment]
this ended up using a bunch of global state and looks nasty, but it does work . . .
