### ISSUE TITLE
Inconsistent context flags

### ISSUE THREAD

**Issue by hdamron17** [jyn514/GrepMe#31]
Why are flags `-a`, `-b`, and `-c` synonyms for `-A`, `-B`, and `-C`, respectively? This doesn't seem to add anything and takes away from flags which could be reserved for other things (in `grep`, `-a` and `-b` are `--text` and `--byte-offset`, respectively, both of which are not needed here). In `grep`, `-c` is a synonym for `--count` which could be a reasonable flag for `grepme`.

Another flag offered by `grep` on ubuntu (although possibly not all) is `-NUM` which is a synonym for `-C NUM`.

Lastly, if consistency is a concern, flag long names in `grep` use an equals sign for parameters, e.g. `--context=5` rather than `--context 5`.

**Comment by jyn514** [comment]
Because I found it convenient. If you want to make a PR adding count as `-c` I'd be happy to take that but since you can replicate easily with `wc -l` I don't think there's a pressing need.

**Comment by hdamron17** [comment]
I agree that `-c` is probably not necessary. I was just confused why `-a`, `-b` and `-c` were used unnecessarily. Is it really that much more convenient to type `-a` than `-A`?

**Comment by jyn514** [comment]
I mean, it's not a big deal, I just like it better.

Anyway, this isn't a feature request (or very actionable) so I'm going to close it.
